  py -u run_mantra.py \
  --is_training 1 \
  --root_path ./dataset/SMAP/ \
  --model_id MaelNetB1_MaelNetS1_SMAP_MSE_NO_SL2 \
  --loss_type mse \
  --model MaelNetB1 \
  --data SMAP \
  --e_layers 2 \
  --d_layers 1 \
  --anomaly_ratio 0.85 \
  --factor 5 \
  --enc_in 25 \
  --dec_in 25 \
  --c_out 25 \
  --d_model 512 \
  --gpu 0 \
  --p_hidden_dims 128 128 \
  --p_hidden_layers 2 \
  --itr 1 &